name: Build Geode Mod

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Geode
        uses: geode-sdk/setup-geode@v1

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release
