name: Build Geode Mod

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone Geode
        run: git clone https://github.com/geode-sdk/geode.git $env:USERPROFILE\geode

      - name: Configure
        run: |
          $env:GEODE_SDK="$env:USERPROFILE\geode"
          cmake -B build

      - name: Build
        run: cmake --build build --config Release
